# -*- coding: utf-8 -*-
"""Assign(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ILfBjfBgMwhspWRKCoNjRngTLHEiBl2

# Exercise 1: Prime Numbers

Write a Python program that checks whether a given number is prime or not. A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.
"""

num = int(input("Enter a number: "))

if num <= 1:
    print("Not prime")
else:
    for i in range(2, num):      # it checks all number from 2 to num-1 as divisors
        if num % i == 0:
            print("Not prime")
            break
    else:
        print("Prime")

"""# Exercise 2: Product of Random Numbers
Develop a Python program that generates two random numbers and asks the user to enter the product of these numbers. The program should then check if the user's answer is correct and display an appropriate message.

"""

import random

# By Using random.randint to Generate two random numbers between 1 and 10
num1 = random.randint(1, 10)
num2 = random.randint(1, 10)

# product of num1 and num2
print("What is", num1, "*", num2, "?")
user_answer = int(input("Enter your answer: "))

# Check the answer
correct_product = num1 * num2

if user_answer == correct_product:
    print("Your answer is correct")
else:
    print("Wrong, The correct answer is", correct_product)

"""# Exercise 3: Squares of Even/Odd Numbers
Create a Python script that prints the squares of all even or odd numbers within the range of 100 to 200. Choose either even or odd numbers and document your choice in the code.

"""

for num in range(100, 201):
    if num % 2 == 0:          # choose EVEN numbers
        print(num, "squared is", num ** 2)

for num in range(100, 201):
    if num % 2 != 0:          # choose ODD numbers
        print(num, "squared is", num ** 2)

"""# Exercise 4:
✅ Problem Statement (Question): Hospital Billing System
A hospital charges its patients based on the following:
•	Room charges per day: ₹2,000
•	Doctor consultation fee (flat): ₹1,500
•	Lab test charges: Based on the number of tests taken. Each test costs ₹300
•	Medicine charges: Total cost of medicines provided
•	Discount: If the total bill (before discount) exceeds ₹10,000, a 10% discount is applied
Write a Python program to calculate the final bill for a patient who:
•	Stayed for 4 days
•	Had 3 lab tests
•	Had medicine charges of ₹2,400

"""

# Hospital Billing System

room_charge_per_day = 2000
doctor_fee = 1500
lab_test_charge_per_test = 300

# Given patient details
days_stayed = 4
num_lab_tests = 3
medicine_charges = 2400

# Calculate individual charges
room_charges = room_charge_per_day * days_stayed
lab_charges = lab_test_charge_per_test * num_lab_tests

# Total before discount
total_before_discount = room_charges + doctor_fee + lab_charges + medicine_charges

# Apply 10% discount if total > 10000
if total_before_discount > 10000:
    discount = total_before_discount * 0.10
else:
    discount = 0

final_bill = total_before_discount - discount

print("Room charges:", room_charges)
print("Doctor consultation fee:", doctor_fee)
print("Lab test charges:", lab_charges)
print("Medicine charges:", medicine_charges)
print("Total before discount:", total_before_discount)
print("Discount applied:", discount)
print("Final bill amount:", final_bill)