# -*- coding: utf-8 -*-
"""Assign(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGe2siGhvy_G6WKrRbXpOt32bCt8DEGr

# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
"""

l1=[5,23,54,8,365]

type(l1)

l1.append(98)

l1

l1.extend([88,56,97])
l1

l1.insert(2,25)
l1

l1.remove(56)
l1

l1.pop(-2)     # using Backward indexing to pop

l1

l1.extend([97,22,97])
l1

l1.count(97)

l1.index(365)

l1.sort()
l1

l1.reverse()
l1

l1

l1.clear()
l1

"""### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why."""

t1=('Rama','Krishna','Vasudeva')

type(t1)

t1[1]

t1[1]='Phani'

"""We know tuple is immutable data type so it is fixed, we can't change or can't perfrom any operation to change the tuple(t1)

only we can do to know the count and index
"""

t1.count('Rama')

t1.index('Vasudeva')

"""### 3.	Create a set of integers with some duplicate values. Print the set and explain the output."""

s1={3,45,98,87,45,365,56,89,3,3,45,2,7,98}

type(s1)

s1

"""Here,s1 it's self sorted and removed the duplicates

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
"""

d1={'name':['Rama','Krishna','Vasudeva'],'age':[25,26,27],'city':['Bangalore','Mumbai','Hyderabad']}

d1

d1['age']=[24,24,24]

d1

d1['email']=['rm@gmailcom','kr@gmailcom','vs@gmailcom']

d1

print(d1)

"""### Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message."""

age=int(input('Enter your age: '))
if age>=18:
    print('You are eligible to vote')
else:
    print('You are not eligible to vote')

"""### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

"""

marks=float(input('Enter your marks: '))
if marks in range(90,101):
  print('Grade:A')
elif marks in range(75,90):
  print('Grade:B')
elif marks in range(50,75):
  print('Grade:C')
elif marks in range(0,50):
  print('Grade:Fail')
else:
  print('Invalid Input')

"""### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative."""

Number=int(input('Enter a number: '))
if Number>0:
  if Number%2==0:
    print('Number is positive and even')
  else:
    print('Number is positive and odd')
elif Number==0:
  print('Number is zero')
else:
  print('Number is negative')

"""## Section B: Numpy

### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10
"""

import numpy as np

scalar=np.array(5)
scalar

arr_1d=np.array([1,2,3,4,5])

arr_1d

arr_1d.ndim    # to know the dimension of array

arr_1d.shape   # to know the shape of array

arr_2d=np.arange(10,70,10).reshape(2,3)

arr_2d

arr_2d.ndim

arr_2d.shape

"""### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint()."""

arr_4d=np.random.randint(0,100,16).reshape(4,4)   # random.randint used for to give numbers randomly in between given range
arr_4d

"""### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'."""

dd=np.array([[1,2,3],[4,5,6],[7,8,9]])
dd

dd.shape

dd.ndim

import pandas as pd

df=pd.DataFrame(dd,columns=['A','B','C'])
df

"""## Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows
"""

d1={'Name':['Ramesh','Suresh','Phani','Shiva','Rakesh','Arvind','Maruthi','James','Mask','Robin'],'Age':[45,44,45,46,46,23,22,24,55,38],'City':['Blr','Mum','Hyd','NYC','Mum','Blr','Hyd','NYC',' UK','NYC'],'Salary':[100000,150000,170000,250000,400000,100000,300000,250000,400000,500000]}

print(d1)

type(d1)

df=pd.DataFrame(d1)
df

df.info()

df.describe()

df[['Name','City']]

df.drop('City',axis=1)   # if we want drop premantly we want to give inplace=True

df

df.fillna(df['Salary'].mean())

df.drop_duplicates()

df.duplicated().sum()

df.isnull().sum()

