# -*- coding: utf-8 -*-
"""Assign(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6ystOoX_561ti83_dqxyBLor1v37ndl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import scipy.stats as stats

df1=pd.read_csv('Billing_Data.csv')
df2=pd.read_csv('Patient_Data.csv')

df1.head()

df2.head()

"""1.	Load the patient dataset and show summary with info()."""

df2.info()

"""2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount']."""

df2[['PatientID','Department','Doctor','BillAmount']]

"""3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime']."""

df2.drop(['ReceptionistID','CheckInTime'],axis=1,inplace=True)

df2.head()

"""4.	Use groupby to find total bill amount per department."""

df2.groupby('Department')['BillAmount'].sum()

"""5.	Remove duplicate patient records based on PatientID."""

df2.duplicated().sum()

df2.drop_duplicates(inplace=True,ignore_index=True)

df2.duplicated().sum()

"""6.	Fill missing BillAmount values with the mean bill amount."""

df2.isnull().sum()

df2.BillAmount.isnull().sum()

df2.BillAmount.mean()

df2.BillAmount.fillna(df2.BillAmount.mean(),inplace=True)

df2.BillAmount.isnull().sum()

df2.isnull().sum()

"""7.	Merge the billing dataset with patient dataset on PatientID.

"""

df3=df2.merge(df1,on='PatientID')

df3

"""8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise)."""

df2

new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Madhu', 'Phani'],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr.Lee', 'Dr.John'],
    'BillAmount': [5500, 4300]
})

full_patient_data = pd.concat([df2, new_patients], ignore_index=True)

full_patient_data

"""9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise)."""

new_columns = pd.DataFrame({
    'InsuranceCovered': [2000, 1500, 2500, 3000, 1000, 1800, 1600],
    'FinalAmount':      [3000, 3500, 5000, 3200, 4000, 3700, 2700]
})

final_dataset=pd.concat([full_patient_data,new_columns],axis=1)

final_dataset

