# -*- coding: utf-8 -*-
"""Assign(3)-Basic Stats1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtcRAdQE68moMiwekopY-lDvwRMk449B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('sales_data_with_discounts.csv')

df.head()

df.columns

df.info()

df_num=df.select_dtypes(exclude='object')
df_num.head()

df.select_dtypes(exclude='object').describe()

df.describe

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np

# Load real dataset
df = pd.read_csv('sales_data_with_discounts.csv')

# 1. Identify numeric columns (simple one-liner)
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print("Numeric columns:", numeric_cols)

# 2. Create histograms for all numeric columns (one command)
plt.figure(figsize=(15, 10))
df[numeric_cols].hist(bins=20, edgecolor='black', alpha=0.7, layout=(2,3))
plt.suptitle('Distribution of Numeric Columns')
plt.tight_layout()
plt.show()

# 3. Quick analysis table
analysis = pd.DataFrame({
    'Column': numeric_cols,
    'Skewness': [stats.skew(df[col].dropna()) for col in numeric_cols],
    'Outliers': [(np.abs(stats.zscore(df[col].dropna())) > 2).sum() for col in numeric_cols]
})
print(analysis)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np

# Load dataset
df = pd.read_csv('sales_data_with_discounts.csv')

# Identify numeric columns
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print("Numeric columns:", numeric_cols)

# 1. Histograms (distribution shape)
plt.figure(figsize=(15, 10))
df[numeric_cols].hist(bins=20, edgecolor='black', alpha=0.7, layout=(2,3))
plt.suptitle('Histograms - Distribution Shape')
plt.tight_layout()
plt.show()

# 2. Box plots (outliers + quartiles) - ADDED
plt.figure(figsize=(15, 8))
df[numeric_cols].boxplot()
plt.title('Box Plots - Outliers & Quartiles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Complete analysis table
analysis = pd.DataFrame({
    'Column': numeric_cols,
    'Skewness': [round(stats.skew(df[col].dropna()), 2) for col in numeric_cols],
    'Outliers': [(np.abs(stats.zscore(df[col].dropna())) > 2).sum() for col in numeric_cols]
})
print("\nAnalysis Summary:")
print(analysis)

