# -*- coding: utf-8 -*-
"""Assign(17).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1u0wvHVlmk8eYLSM-4PPBd0TsIy0K3v
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""Part 1: Data Preparation and Exploration"""

# Load the dataset
# Assuming 'date' column needs to be parsed as datetime
df = pd.read_csv('exchange_rate.csv')
df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df.set_index('date', inplace=True)

# Initial Exploration
plt.figure(figsize=(10, 5))
plt.plot(df['Ex_rate'], label='USD to AUD')
plt.title('Historical Exchange Rate: USD to Australian Dollar')
plt.legend()
plt.show()

# Preprocessing: Check for missing values
print("Missing values:\n", df.isnull().sum())
df = df.fillna(method='ffill') # Forward fill if any missing values exist

"""Part 2: Model Building - ARIMA"""

# Check for stationarity and difference if necessary (d parameter)
# Plotting ACF and PACF for parameter selection
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
plot_acf(df['Ex_rate'], ax=ax1)
plot_pacf(df['Ex_rate'], ax=ax2)
plt.show()

# Model Fitting (Example parameters: p=1, d=1, q=1)
model = ARIMA(df['Ex_rate'], order=(1, 1, 1))
model_fit = model.fit()

# Diagnostics: Residual analysis
model_fit.plot_diagnostics(figsize=(10, 8))
plt.show()

# Forecasting
forecast_steps = 30
forecast = model_fit.get_forecast(steps=forecast_steps)
forecast_df = forecast.summary_frame()

plt.figure(figsize=(10, 5))
plt.plot(df['Ex_rate'].tail(100), label='Actual')
plt.plot(forecast_df['mean'], label='Forecast', color='red')
plt.fill_between(forecast_df.index, forecast_df['mean_ci_lower'], forecast_df['mean_ci_upper'], color='pink', alpha=0.3)
plt.legend()
plt.show()

"""Part 3: Evaluation and Comparison"""

def calculate_mape(actual, pred):
    return np.mean(np.abs((actual - pred) / actual)) * 100

# For demonstration, comparing model fit against training data
actual = df['Ex_rate'].values
predicted = model_fit.predict()

mae = mean_absolute_error(actual, predicted)
rmse = np.sqrt(mean_squared_error(actual, predicted))
mape = calculate_mape(actual, predicted)

print(f"MAE: {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAPE: {mape:.2f}%")

"""Summary

 - Data Loading: Parse dates and handle missing values.
 - Exploration: Visualize trends and seasonality.
 - ARIMA Modeling: Select parameters(p, d, q) using ACF/PACF and fit the model.
 - Forecasting: Generate out-of-sample predictions.
 - Evaluation: Compare performance using MAE, RMSE, and MAPE

Deliverables:

Visualizations: Plots for time series trends, ACF/PACF, residuals, and final forecasts.

Python Code: A well-commented script executing the data cleaning and modeling.

Explanations: Rationales for the chosen ARIMA parameters and an analysis of model diagnostics

Assessment Criteria:

Accuracy: Correctness of the data preparation steps.

Justification: Clear reasoning for model selection and parameter tuning.

Depth of Analysis: Quality of diagnostic checks and error metric interpretation.
"""

